spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.77.37.145:3306/new_schema?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: NOT_EMPTY
      db-type: MYSQL
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


rocketmq:
  consumer:
    groupName: consumerGroup
    consumeThreadMin: 2
    consumeThreadMax: 5
    consumeMessageBatchMaxSize: 10
    topics: rocketTopic,rocketTag
    name-server: 127.0.0.1:9876
  producer:
    groupName: producerGroup
    maxMessageSize: 100
    sendMsgTimeout: 1000
    retryTimesWhenSendFailed: 3
    name-server: 127.0.0.1:9876
  name-server: 127.0.0.1:9876


redis:
  host: localhost
  port: 6379





